version: '3'

services:
  
  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM=php-fpm
        - NGINX_USER=${NGINX_USER}
        - NGINX_GROUP=${NGINX_GROUP}
    volumes:
      - ${APP_PATH}:/var/www
      # 挂载日志目录
      - ${NGINX_LOG_PATH}:/var/log/nginx
      # 挂载虚拟主机配置目录
      - ${NGINX_SITES_PATH}:/etc/nginx/vhost
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - cphfd
      - cphbd




  php-fpm:
    build:
      context: ./php-fpm
      args:
        - INSTALL_SOAP=${INSTALL_SOAP}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        - INSTALL_SWOOLE=${INSTALL_SWOOLE}
        - INSTALL_OPCACHE=${INSTALL_OPCACHE}
        - INSTALL_EXIF=${INSTALL_EXIF}
        - INSTALL_MYSQLI=${INSTALL_MYSQLI}
        - INSTALL_MEMCACHED=${INSTALL_MEMCACHED}
        - INSTALL_BCMATH=${INSTALL_BCMATH}
        - INSTALL_MONGO=${INSTALL_MONGO}
        - INSTALL_ZIP_ARCHIVE=${INSTALL_ZIP_ARCHIVE}
        - INSTALL_PHPREDIS=${INSTALL_PHPREDIS}
        - INSTALL_INTL=${INSTALL_INTL}
        - INSTALL_LDAP=${INSTALL_LDAP}
    volumes:
      - ${APP_PATH}:/var/www
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
    networks:
      - cphbd



  mysql:
    build:
      context: ./mysql
    environment:
      # 启动时创建的数据库
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - cphfd
      - cphbd



  mongo:
    build:
      context: ./mongo
    ports:
        - "${MONGOD_PORT}:27017"
    volumes:
        - ${DATA_PATH}/mongo:/data/db
    networks:
      - cphbd




  phpmyadmin:
    build: ./phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - mysql
    networks:
      - cphfd
      - cphbd



  memcached:
    build: ./memcached
    volumes:
      - ${DATA_PATH}/memcached:/var/lib/memcached
    ports:
      - "${MEMCACHED_PORT}:11211"
    networks:
      - cphbd



  redis:
    build: ./redis
    volumes:
      - ${DATA_PATH}/redis:/data
    ports:
      - "6379:6379"
    networks:
      - cphbd
  
networks:
  cphfd:
    driver: bridge
  cphbd:
    driver: bridge


